<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_logout</name>
   <tag></tag>
   <elementGuidId>f02dcdb8-9a7f-476e-bfac-3bfbbc391f6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@class='dropdown-item']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@class='dropdown-item']</value>
      <webElementGuid>2f0c891d-6730-4ce9-bdbb-ce7f6cd7de0e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
