<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ADMINISTRATOR logout</name>
   <tag></tag>
   <elementGuidId>eebf6b3f-5d3f-4826-8c13-921ed4ff5986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='dropdown-toggle' and @style='padding-top: 18px; padding-bottom: 18px;']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>afbb2c43-7965-4770-9605-9467d4cf99de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>945358bb-6587-410c-a411-876f6137b144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle</value>
      <webElementGuid>74b79c96-a251-447f-8664-e63ce67ec691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>35f5e6e9-9219-4059-93e0-a2f0e9d80b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    ADMINISTRATOR
                anna.dedvukaj@infinicept.com 
            </value>
      <webElementGuid>08b1dada-043d-4442-a48c-dde9d0ba1b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;app&quot;]/header[1]/nav[@class=&quot;navbar navbar-inverse navbar-static-top hidden-print&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;float-right&quot;]/div[@class=&quot;dropdown&quot;]/a[@class=&quot;dropdown-toggle&quot;]</value>
      <webElementGuid>bf1f9062-a596-4129-af1f-9d41ea8f08c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v2017.425.8476.28577'])[1]/following::a[1]</value>
      <webElementGuid>6dff984e-0dd9-4a4b-a442-b013ff777512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::a[2]</value>
      <webElementGuid>f59d5f98-5e99-4309-be12-77ecdf0474b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='anna.dedvukaj@infinicept.com']/parent::*</value>
      <webElementGuid>2e847f84-441c-44b5-ad55-660e219613fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>39f8715f-803b-4e71-bdf8-f8982e69e6c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>42141b28-ee69-42dc-90d5-19c173e677ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '
                    ADMINISTRATOR
                anna.dedvukaj@infinicept.com 
            ' or . = '
                    ADMINISTRATOR
                anna.dedvukaj@infinicept.com 
            ')]</value>
      <webElementGuid>e4239364-aef5-45a5-9550-37d0b25b3344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//a[@class='dropdown-toggle' and @style='padding-top: 18px; padding-bottom: 18px;']</value>
      <webElementGuid>0cd62616-c94e-4831-806e-81a9d479efcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
