<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>78f33f02-e6a8-4808-a239-5416e881077e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='submitButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;submitButton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dbb08d32-20fd-4792-a0ee-4a2c3b737441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-lg pull-left</value>
      <webElementGuid>a7a02bc6-73bd-41f5-98f3-74a3db6bb09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>f2166215-47bc-4f72-b453-1b74334af885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>c9d23e05-23fe-4cd8-88ee-285214c4d9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submitButton</value>
      <webElementGuid>8739e922-3ffa-4476-9e6d-e5d214c43bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>83665583-4b54-4a23-bad2-b2cb00d67562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>601f6eff-47b4-43d0-92d1-6eff8ad2379c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths todataurljpeg todataurlwebp&quot;]/body[@class=&quot;account&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;identity&quot;]/div[@class=&quot;group&quot;]/form[1]/div[@class=&quot;form-group clearfix&quot;]/div[2]/button[@class=&quot;btn-lg pull-left&quot;]</value>
      <webElementGuid>f56ef851-270c-4683-9939-4979e13ab798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='submitButton']</value>
      <webElementGuid>a2e31ce2-88d8-4b8f-bc12-a3969c87cbbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is your email address?'])[1]/following::button[1]</value>
      <webElementGuid>bb35f2ca-f5e9-469d-b4f5-08eccbea84e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>1bc81f82-9a98-46b4-9847-e92d0d58a406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'submitButton' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>46f59a31-2323-443b-bb11-49552329821f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
