<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>e1ea71b8-9aa9-47e6-9260-0cf7879df9fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='submitButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;submitButton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c5b5b2b-2cf9-4b90-83b4-05373756b979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-lg pull-left</value>
      <webElementGuid>636839ce-1024-4cdb-9105-0ea106f7fc92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>2e731916-bd15-49b8-b4fd-977e527c0c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>125d5e68-df5f-4430-8a58-bfdee9d8c49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submitButton</value>
      <webElementGuid>9eeed598-a907-4063-988d-ad675cfd2bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>72671cd8-5188-41be-883d-a6f2fd7d7026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>9e390be3-d742-4649-b08b-dff7ee2088fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths todataurljpeg todataurlwebp&quot;]/body[@class=&quot;account&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;identity&quot;]/div[@class=&quot;group&quot;]/form[1]/div[@class=&quot;form-group clearfix&quot;]/div[2]/button[@class=&quot;btn-lg pull-left&quot;]</value>
      <webElementGuid>3c0f0882-75a7-413a-8e09-1a25c1751352</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='submitButton']</value>
      <webElementGuid>0946002f-f616-449f-8426-2ab480d1e6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is your email address?'])[1]/following::button[1]</value>
      <webElementGuid>e8d7bbbb-29ae-4514-9fb0-bfa5cd871c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c6b311ba-0aed-456f-81a7-955aad319c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'submitButton' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>b6f616f3-5713-4fc5-b0bb-7bc3753e70d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
