<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_admin</name>
   <tag></tag>
   <elementGuidId>9b35720f-d5c6-4156-9c51-072e6b70c340</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//strong[normalize-space()='ADMINISTRATOR']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//strong[normalize-space()='ADMINISTRATOR']</value>
      <webElementGuid>6ee9096b-a0c5-41d8-9f9f-cf39c016f210</webElementGuid>
   </webElementProperties>
</WebElementEntity>
