<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>3072e3ea-647e-4f88-a81e-e124628d5b08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Logout')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e2e855cc-d17b-4b64-b6bd-dfcd6906fe3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>03c4144a-990a-4ab5-8cbf-881d8deb0e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/system/UserAccount/Logout</value>
      <webElementGuid>30ae7b9b-cde0-4b44-90e8-a2295a4cc73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>2d26e22b-536e-47b2-8d5c-5e94ca1e3c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths todataurljpeg todataurlwebp&quot;]/body[@class=&quot;app&quot;]/header[1]/nav[@class=&quot;navbar navbar-inverse navbar-static-top hidden-print&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;float-right&quot;]/div[@class=&quot;dropdown show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-right show&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>46fe96d9-4266-4ca6-9c70-740c93b194cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Logout')]</value>
      <webElementGuid>49057091-9e73-4287-a19e-884ec436cc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMINISTRATOR'])[1]/following::a[2]</value>
      <webElementGuid>bd4ce392-346a-4710-8c0e-6c11b46903af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading, please wait...'])[1]/following::a[4]</value>
      <webElementGuid>8f98d10e-7a91-4a19-ab68-e956b96bef1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin home'])[1]/preceding::a[1]</value>
      <webElementGuid>0765d38b-cb5e-46a0-94ea-9f611ac6a5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>1351f24b-5706-4e50-be4a-d5c7fc1b3b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/system/UserAccount/Logout')]</value>
      <webElementGuid>6d519d38-5d27-4228-a9d5-0950ae316d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>2c914fe9-9d51-46fc-8bd1-906fb93d3cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/system/UserAccount/Logout' and (text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>263b2b62-5188-4a93-ab93-46ad70513c07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
